### ISSUE TITLE
Learning doesn't work when following the lab, it calls the new animal `null`

### ISSUE THREAD

**Issue by MrCsabaToth** [firebase/assistant-codelab#4]
Workaround: importing the Assistant.zip from solution solves the problem.
The reason is that when I create my own "Guess is Correct" intent, I just add an input context `guess` to it. The intent provided by the solution has a more complete context setup, which includes the `welcome` context as output.

**Comment by MrCsabaToth** [comment]
Although theoretically we don't even touch "Guess is Correct" intent in this scenario, so it might be some glitch in the system. Which can be easily reproduced by this lab fortunately.

**Comment by joaquinperaza** [comment]
hi @MrCsabaToth I imported Assistant.zip from solution but it still show null, i dont know if its a bug or a challenge 👍

**Comment by MrCsabaToth** [comment]
@joaquinperaza that's interesting. Are you using your own Firebase functions backend?

**Comment by SFurtwangler** [comment]
I had the same problem, even after loading the Assistant.zip from the solution. 
I saw https://github.com/firebase/assistant-codelab/issues/5 which seemed incorrect but I tried it anyway, and it was then able to identify the animal but got all confused in the next step where the question would be supplied. 

Based on the json for the step where I name the animal, I would expect that `const new_thing = assistant.getArgument(GUESSABLE_THING_PARAM);` would work:

```
...
  "result": {
    "source": "agent",
    "resolvedQuery": "I'm thinking of a lizard.",
    "action": "learn-thing",
    "actionIncomplete": false,
    "parameters": {
      "guessable-thing": "lizard"
    },
...
```

**Comment by joaquinperaza** [comment]
I have finally solved with #5

Enviado desde mi iPhone

**Comment by SFurtwangler** [comment]
Another note: I moved on (put the code back the way the tutorial tells you to) and tested the app on an actual Google Home device and it worked correctly but still doesn't work in the API.AI "Try it Now" panel on the right. 

I am not sure if it is related but I also see `actions-on-google:debug isNotApiVersionOne_` in the logs when using the Try it Now panel but not when speaking to a device.
